// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6IZhioSa0rHrArRBMIuaIa7_dSnm23Q',
    appId: '1:218370738576:web:e2791bff296816a8b44b15',
    messagingSenderId: '218370738576',
    projectId: 'plantity-6808e',
    authDomain: 'plantity-6808e.firebaseapp.com',
    storageBucket: 'plantity-6808e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABq_S5uUTNBuIs_ZxmYwzX2eSzBgGF_9I',
    appId: '1:218370738576:android:7e0c85ddb2a32e32b44b15',
    messagingSenderId: '218370738576',
    projectId: 'plantity-6808e',
    storageBucket: 'plantity-6808e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZt9oVBoxXYNXTG922kkGLBTwhnfYuab8',
    appId: '1:218370738576:ios:fc9a8c21bd9a0646b44b15',
    messagingSenderId: '218370738576',
    projectId: 'plantity-6808e',
    storageBucket: 'plantity-6808e.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZt9oVBoxXYNXTG922kkGLBTwhnfYuab8',
    appId: '1:218370738576:ios:e9b6259c3925a672b44b15',
    messagingSenderId: '218370738576',
    projectId: 'plantity-6808e',
    storageBucket: 'plantity-6808e.appspot.com',
    iosBundleId: 'com.example.plantApp.RunnerTests',
  );
}
